### ISSUE TITLE
Current ModLoader.Version doesn't follow semantic versioning

### ISSUE THREAD

**Issue by Banane9** [resonite-modding-group/ResoniteModLoader#13]
With the current changes from tag 2.6.0, the enum member `IncompatibleConfigurationHandlingOption.FORCE_LOAD` was removed. This is technically breaking backwards compatibility and as such would warrant a version bump to 3.0.0.

https://github.com/resonite-modding-group/ResoniteModLoader/compare/2.6.0...main

**Comment by XDelta** [comment]
The changes you are referring to were committed after the Version string change. Additionally, I haven't found any mods using the older option and it has been obsolete since October. Hasn't been a release made for these changes and still a small few pending commits. Will be changing to a 3.0.0 anyway for the typing changes.
